# espanso match file

matches:
  # Simple text replacement
  - trigger: ":-"
    replace: "—"
  - trigger: ":email"
    replace: "dylanlazarov2002@protonmail.com"
 

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!
  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
